### PR TITLE
our only tree covering arachnids rejects monophyly

### PR DESCRIPTION
**Pull request by mtholder**
See https://tree.opentreeoflife.org/curator/study/view/pg_1340/?tab=trees&tree=tree2669 for the tree that rejects monophyly

### CODE REVIEW

**Comment by kcranston** [comment]
I don't think we should remove that test just because the synthetic tree doesn't currently support that taxon (unless we have evidence / feedback that the node is indeed not monophyletic).

**Comment by mtholder** [comment]
so currently the propinquity build fails if the monophyly tests fail. we just need to figure out if we want to suppress that behavior.

**Comment by kcranston** [comment]
I don't think synthesis should fail, it should just produce a report of what monophyly & inclusion tests fail (in a "Yes, we know that Arachnids should probably be in there, but they aren't and here is why" sort of way).

**Comment by mtholder** [comment]
how is it supposed to know which taxa "should probably be in there"? I thought the monophyly tests were supposed to be tests. We now have propiquinty listing all of the contested taxa (which is a superset of all of the taxa that are not monophyletic. So it is easy to look up why any taxon is not monophyletic.  Do we not want any tests that the tree has to pass?

**Comment by kcranston** [comment]
I see your point about having the contested taxa list. The monophyly tests came from curator statements about what taxa they expected to see in the tree. It pre-dates the current reporting about contested taxa. Couple of ways to handle the list of tests:

1. Remove tests that do not pass (with the assumption that the monophyly statement is erroneous?)
1. Remove input trees that conflict with the tests (effectively making the tests into constraints)
1. Use the list as a reporting mechanism, rather than a test. Given that we have a list of contested taxa, this would merely serve as a way to highlight key taxa based on user interest.  
1. Get rid of the monophyly tests entirely and simply report the list of contested taxa

**Comment by mtholder** [comment]
I should have pointed out a few more things:

  1. the "offending" tree was added since v5.0 the commit was https://github.com/OpenTreeOfLife/collections-1/commit/471011a753d6c3a27be75674847e7628164ca36a on May 4

  2. the synthesis tree is still produced, but it is only the fact that `make check` fails now. We can easily allow monophyly tests to fail and still let make check to pass if we want.

  3. this does not seem to be an OTU mapping or rooting problem, though authors of the study express some skepticism that the result that Pycnogonids nest inside Arachnida is correct.

**Comment by jar398** [comment]
I think the right way to handle this is to have two kinds of tests,
necessary and prospective (I just made up that terminology). A necessary
test is one that has passed in the past, or that is a show-stopper for the
next checkin. A prospective one is for a feature that is under long-term
development, but has never passed, so should not hold up other progress
(such as releases). When a prospective test passes there should be some
procedure that promotes it to a necessary test.

In this case, since we have two clients for the tests, a given test can be
either necessary or prospective for either client.

**Comment by pmidford** [comment]
I am probably responsible for adding the Arachnida test. I agree that
the result placing Pycnogonids within Arachnida is rather odd, but
Pycnogonida's placement has been controversial for nearly 10 years now.
Though the question is usually whether they are basal Chelicerates or not.

**Comment by kcranston** [comment]
We agreed on our weekly hangout that there was enough uncertainty about the monophyly of this clade to remove the test

**Pull request merged**
