### PR TITLE
Updates to phylesystem statistics report

### PR DESCRIPTION
**Pull request by pmidford**
update datestamp format and write json results to a temp file to minimize filesystem full problems

### CODE REVIEW

**Comment by pmidford** [comment]
@jimallman may want to review the fields in the json produced here - not too late to cut some out.

**Comment by jimallman** [comment]
I'm hesitant to remove fields that might be of interest to others, assuming they're clearly documented. That said, only two of these fields are **currently used** by the main webapp:
- unique_OTU_count
- nominated_study_unique_OTU_count

All the rest are **currently unused** by the webapp, in server- or client-side code:
- OTU_count
- nominated_study_OTU_count
- nominated_study_count
- nominated_study_unmapped_OTU_count
- reported_study_count
- run_time
- study_count
- unmapped_OTU_count

**Comment by pmidford** [comment]
There seemed to be consensus about removing run_time on Wednesday.  I'll leave the rest for now.

**Comment by jar398** [comment]
I thought we were talking about removing things from the UI. There's no
reason to remove things from the underlying json files (except maybe if
they're false).

-- apologies for brevity / using handheld gizmo --

On Aug 21, 2015, at 11:30, Peter Midford <notifications@github.com> wrote:

There seemed to be consensus about removing run_time on Wednesday. I'll
leave the rest for now.

—
Reply to this email directly or view it on GitHub
<https://github.com/OpenTreeOfLife/germinator/pull/27#issuecomment-133463572>
.

**Pull request merged**
