### PR TITLE
Plan for moving files server to S3

### PR DESCRIPTION
**Pull request by jar398**
Mainly look at [the README](https://github.com/OpenTreeOfLife/germinator/blob/1527585c59295a7982a622cef9e0e8d6b8311614/files-server/README.md)

### CODE REVIEW

**Comment by jar398** [comment]
Intended to address #126 (when plan is executed)

**Comment by mtholder** [comment]
We've changed a few things about files since it moved, so this doesn't work as it. But this branch has some nice documentation. So, I'm going to delete the PR for now and leave the branch.

**Comment by mtholder** [comment]
(sorry "close the PR" not "delete the PR")

**Comment by jimallman** [comment]
Thanks for taking a closer look. What needs to happen to preserve the docs (I assume you mean [
this new stuff in `file-server/README.md`](https://github.com/OpenTreeOfLife/germinator/pull/127/files#diff-d5d9ab61ddc986d00db26098963be662))? Should we make/assign an issue for this?

**Comment by mtholder** [comment]
good idea. I created https://github.com/OpenTreeOfLife/germinator/issues/156 when files comes back on line, I can walk through it and check the docs from this PR against the current system.

**Pull request closed without merging**
